version: '3.3'

services:

  shop-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
    ports:
      - "3308:3306"

  shop-web-site_back:
    build: ./
    container_name: shop-web-site_back
    ports:
      - "8083:8083"
    restart: always
